### PR TITLE
Implement recovery button, encumbrance, and automatic DR

### PR DESCRIPTION
**Pull request by MulliganStu**
The text on the character sheet that says, "Recover 1d8+BODY" under hit points is now clickable and will auto-heal the character. The text will light up when hovered over as well, similar to clicking BODY, DEXTERITY, etc. Also will auto pull the DR of targetted actor when attacking.

### CODE REVIEW

**Comment by MulliganStu** [comment]
This resolves my issues [44](https://github.com/fvtt-fria-ligan/deathinspace-foundry-vtt/issues/44) & [42](https://github.com/fvtt-fria-ligan/deathinspace-foundry-vtt/issues/42)

**Comment by MulliganStu** [comment]
Removed unused value

**Comment by MulliganStu** [comment]
This should solve [Issue 18](https://github.com/fvtt-fria-ligan/deathinspace-foundry-vtt/issues/18)

**Comment by MulliganStu** [comment]
Added a portion that sets DR automatically based on DEX and items, which solves [Issue 9](https://github.com/fvtt-fria-ligan/deathinspace-foundry-vtt/issues/9)

**Comment by mcglincy** [comment]
Thanks for adding this! I don't have cycles to manually test this, but I'll assume you did :)

**Pull request merged**
